name: darwin-Libsystem

on:
  push:
  pull_request:

jobs:
  nix-build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, macos-12, macos-11]
        pkgs: [release-23.11, release-23.05, release-22.11, release-22.05, release-21.11, release-21.05]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - run: ./build-darling.sh 'https://github.com/NixOS/nixpkgs/archive/${{ matrix.pkgs }}.tar.gz'
